version: "3.7"
services:
  mirakurun:
    image: chinachu/mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    ports:
      - "40772:40772"
      - "9229:9229"
    volumes:
      - ./mirakurun/conf:/app-config
      - ./mirakurun/data:/app-data
      # support recpt1 command
      # https://github.com/Chinachu/Mirakurun/blob/master/doc/Platforms.md#-how-to-use-non-dvb-devices
      # https://github.com/Chinachu/Mirakurun/blob/master/docker/docker-compose.yml
      - ./mirakurun/opt/:/opt/
    environment:
      TZ: "Asia/Tokyo"
    devices:
      - /dev/bus:/dev/bus
      - /dev/px4video2
      - /dev/px4video3
      - /dev/px4video6
      - /dev/px4video7
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m

  mysql:
    image: mariadb:10.5
    # image: mysql:8.0 # 囲み文字を使用する場合
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_USER: epgstation
      MYSQL_PASSWORD: epgstation
      MYSQL_ROOT_PASSWORD: epgstation
      MYSQL_DATABASE: epgstation
      TZ: "Asia/Tokyo"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1 # for mariadb
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --performance-schema=false --expire_logs_days=1 --default-authentication-plugin=mysql_native_password # for myql
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  epgstation:
    container_name: epgstation
    # build:
    #   context: "./epgstation"
    #   dockerfile: "qsv.cmcut.Dockerfile"
    image: ghcr.io/eginoy/epgstation-qsv-jlse/epgstation-qsv-jlse:latest
    volumes:
      - ./epgstation/config:/app/config
      - ./epgstation/data:/app/data
      - ./epgstation/thumbnail:/app/thumbnail
      - ./epgstation/logs:/app/logs
      - ./join_logo_scp_trial/JL:/join_logo_scp_trial/JL
      - ./join_logo_scp_trial/logo:/join_logo_scp_trial/logo
      - ./join_logo_scp_trial/result:/join_logo_scp_trial/result
      - ./join_logo_scp_trial/setting:/join_logo_scp_trial/setting
      - ./join_logo_scp_trial/src:/join_logo_scp_trial/src 
      - /mnt/hdd1tb/recorded:/app/recorded
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - mirakurun
      - mysql
    ports:
      - "8888:8888"
      - "8889:8889"
    #         user: "1000:1000"
    devices:
      - /dev/dri:/dev/dri
    restart: always

volumes:
  mysql-db:
    driver: local
